option(LUTEFISK3D_HEADLESS "Build without renderer component" OFF)
option(LUTEFISK3D_SOUND "Build with audio component" ON)
option(LUTEFISK3D_INPUT "Build wit input component" ON)
option(LUTEFISK3D_UI "Build with UI component" ON)
option(LUTEFISK3D_IK "Inverse kinematics subsystem enabled" ON)
option(LUTEFISK3D_NAVIGATION "Navigation subsystem enabled" ON)
option(LUTEFISK3D_PHYSICS "Physics subsystem enabled" ON)
option(LUTEFISK3D_2D "2D subsystem enabled" ON)
option(LUTEFISK3D_NETWORK "Networking subsystem enabled" ON)
option(LUTEFISK3D_PROFILING "Profiler support enabled" ON)
option(LUTEFISK3D_TOOLS "Tools enabled" ON)
option(LUTEFISK3D_EXTRAS "Build extra tools" ON)
option(LUTEFISK3D_SSE "Enable SSE instructions" ON)
option(LUTEFISK3D_SAMPLES "Build samples" ON)
option(LUTEFISK3D_LOGGING "Enable logging subsystem" ON)
option(LUTEFISK3D_SYSTEMUI "Build SystemUI subsystem" ON)
option(LUTEFISK3D_PACKAGING "Package resources" ON)
option(LUTEFISK3D_FILEWATCHER "Watch filesystem for resource changes" ON)
option(LUTEFISK3D_PLUGINS "Enable native plugins" ON)
option(LUTEFISK3D_HASH_DEBUG "Enable StringHash name debugging" OFF)

if (LUTEFISK3D_TOOLS)
    #set (LUTEFISK3D_SYSTEMUI ON)
    set (LUTEFISK3D_FILEWATCHER ON)
    set (LUTEFISK3D_LOGGING ON)
    if (NOT DEFINED LUTEFISK3D_HASH_DEBUG)
        set (LUTEFISK3D_HASH_DEBUG ON)
    elseif (NOT LUTEFISK3D_HASH_DEBUG)
        message (WARNING "Editor uses LUTEFISK3D_HASH_DEBUG feature, but it was disabled. Editor will still build but some features will break.")
    endif ()
endif ()
